hydra:
  run:
    dir: .
  output_subdir: ${checkpoint_dir}


defaults:
  - base
  - dataset: image
  - model: magicpony


dataset:
  batch_size: 10
  test_data_dir: data/magicpony/bird_videos_bonanza/test
  load_dino_feature: true
  dino_feature_dim: 16
  num_frames: 1


model:
  cfg_predictor_instance:
    cfg_pose:
      max_trans_xy_range_ratio: 0.5
      lookat_zeroy: false
    cfg_articulation:
      num_legs: 0
      num_leg_bones: 0
      static_root_bones: true
      max_arti_angle: 45


run_train: false
run_test: true
checkpoint_dir: results/magicpony/pretrained_bird
checkpoint_name: pretrained_bird.pth


# Visualization
output_dir: results/magicpony/pretrained_bird/visualization
resolution: 256
render_modes: [input_view, other_views, rotation]
finetune_texture: false
finetune_iters: 10
finetune_lr: 0.001
evaluate_keypoint: false

