hydra:
  run:
    dir: .
  output_subdir: ${checkpoint_dir}


defaults:
  - base
  - dataset: image
  - model: magicpony


dataset:
  in_image_size: 256
  out_image_size: 256
  batch_size: 10
  train_data_dir: data/magicpony/horse_combined/train
  val_data_dir: data/magicpony/horse_combined/test
  random_shuffle_samples_train: true
  load_dino_feature: true
  dino_feature_dim: 16


run_train: true
run_test: false
seed: 0
gpu: 0
num_iters: 140000
checkpoint_dir: results/magicpony/horse
resume: true
logger_type: wandb